name: default
channels:
  - lebedov
  - bioconda
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - lf
  - git-lfs
  - gofasta
  - snakemake
  - pip>=22.1.2
  - python>=3.10
  - usher>=0.5.4
  - minimap2>=2.16
  - biopython>=1.74
  - nextclade>=2.2.0
  - ucsc-fatovcf>=426
  - pip:
    - mpire
    - arrow 
    - pandas 
    - Cython
    - pytools
    - pendulum 
    - openpyxl 
    - fuzzyset 
    - biopython 
    - ultraimport
    - python-dotenv
    - more-itertools
    - websocket-client
    - git+https://github.com/cov-lineages/pangolin-data.git
    - git+https://github.com/cov-lineages/scorpio.git
    - git+https://github.com/cov-lineages/constellations.git
    - git+https://github.com/cov-lineages/pangolin.git
